#!/bin/bash
# New York, Chicago, Los Angeles, San Francisco
retdir=$1
simtype=$2
if [ ! -d $retdir ]; then
	mkdir $retdir
fi

for simnum in "5" "10" "20" "50" "100"
do 
	for sigma in "7200" "3600" "1800" "900"
	do
		for city in "NY 27485069891a7938" "CH 1d9a5370a355ab0c" "LA 3b77caf94bfc81fe" "SF 5a110d312052166f"
		do
			set -- $city
			echo Running $1 $simnum $sigma on ${simtype}
			./ppython twhere.py $2 $simnum $sigma >$retdir/$1_sm${sigma}_in${simnum}_${simtype}.result
		done
	done
done
