#!/usr/bin/env bash
# New York, Chicago, Los Angeles, San Francisco
set -e
retdir=$1
model=$2
if [ ! -d $retdir ]; then
	mkdir $retdir
fi
veclen=100
if [ $model == "colfilter" ]; then
	for simnum in 100 50 20 10 5
	do 
		for sigma in 7200. 3600. 1800. 900. 450.
		do
			for city in "NY 27485069891a7938" "CH 1d9a5370a355ab0c" "LA 3b77caf94bfc81fe" "SF 5a110d312052166f"
			do
				set -- $city
				#echo Running $1 $simnum $sigma on ${simtype}
				#./ppython twhere.py $2 $simnum $sigma >$retdir/$1_sm${sigma}_in${simnum}_${simtype}.result
				echo Running $1
				python twhere.py $2 category colfilter "{'simnum':$simnum,'similarity':CosineSimilarity(),'aggregator':LinearCombination(),'smoothing':True}" "{'veclen':$veclen,'interval':(0.,24*3600.),'kernel':'gaussian','params':($sigma,),'isaccum':False}" > $retdir/$1_cosprob_n$(printf "%03d" $simnum)_s$(printf "%04.0f" $sigma).result 2> $retdir/log
			done
		done
	done
else
	for city in "NY 27485069891a7938" "CH 1d9a5370a355ab0c" "LA 3b77caf94bfc81fe" "SF 5a110d312052166f"
	do
		set -- $city
		#echo Running $1 $simnum $sigma on ${simtype}
		#./ppython twhere.py $2 $simnum $sigma >$retdir/$1_sm${sigma}_in${simnum}_${simtype}.result
		echo Running $1
		python twhere.py $2 category $model > $retdir/$1_${model}.result
	done
fi

